import{a as f,S as y,i}from"./assets/vendor-D9tHNiur.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const L="49001064-c7b72e374a4ae6399075933f6",w="https://pixabay.com/api/";let l=1,E=1;function v(){l=1}async function p(r){const t={key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:l};try{const o=await f.get(w,{params:t});return E=Math.ceil(o.data.totalHits/40),l+=1,o.data}catch(o){throw console.error("Error fetching images:",o),o}}const g=document.querySelector(".loader");function h(){g.classList.remove("hidden")}function m(){g.classList.add("hidden")}function I(){document.getElementById("gallery").innerHTML=""}function u(r){const t=document.getElementById("gallery");r.forEach(s=>{const e=document.createElement("li");e.classList.add("gallery-item"),e.innerHTML=`
      <a href="${s.largeImageURL}" class="gallery-link">
          <img src="${s.webformatURL}" alt="${s.tags}" class="gallery-image" />
      </a>
      <div class="info">
          <p>Likes <span>${s.likes}</span></p>
          <p>Views <span>${s.views}</span></p>
          <p>Comments <span>${s.comments}</span></p>
          <p>Downloads <span>${s.downloads}</span></p>
      </div>
  `,t.appendChild(e)}),new y(".gallery-link",{captionsData:"alt"}).refresh()}function P(){const r=document.querySelector(".gallery-item");if(r){const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}const b=document.getElementById("search-form"),R=document.getElementById("search-input");document.querySelector(".loader");const a=document.getElementById("load-more");let c="";b.addEventListener("submit",async r=>{if(r.preventDefault(),c=R.value.trim(),c===""){i.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}I(),a.classList.add("hidden"),h(),v();try{const t=await p(c),o=t.hits,s=Math.ceil(t.totalHits/40);o.length===0?i.error({title:"Error",message:"No images found. Try another search!",position:"topRight"}):(u(o),l<s?a.classList.remove("hidden"):a.classList.add("hidden"))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{m()}});a.addEventListener("click",async()=>{a.classList.add("hidden"),h();try{const r=await p(c),t=r.hits,o=Math.ceil(r.totalHits/40);if(t.length===0||l>=o){i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}else u(t),P(),l<o?a.classList.remove("hidden"):(a.classList.add("hidden"),i.info({title:"Info",message:"No more images to load.",position:"topRight"}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
